use CustomerAnalysis;
select * from behavior;

# total reveneue generated by male vs female customers
select gender,sum(purchase_amount) from behavior
group by gender;

#which customer used discount but still spent more than the average purhcase
select customer_id, purchase_amount from behavior
where discount_applied="Yes" and purchase_amount>=(select avg(purchase_amount) from behavior);

#top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2 )as average_rating from behavior 
group by item_purchased
order by average_rating desc limit 5;

# compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount) as average_purchaseamount from behavior
where shipping_type in ("Express","Standard")
group by shipping_type;

#Do subscriber spend more?Compare average spend and total revenue between subscriber and non-subscriber
select subscription_status,count(customer_id),avg(purchase_amount) as avergae_spend, sum(purchase_amount) as total_spend from behavior
group by subscription_status
order by total_spend desc ;

#Highest selling item with the discount applied
select item_purchased,count(item_purchased) as item from behavior
where discount_applied="Yes"
group by item_purchased
order by item desc limit 5;

#Highest percentage of purchase with discount applied
select item_purchased,
Round(100 * sum(case when discount_applied="Yes" Then 1 else 0 end)/count(*),2) as discount_rate
from behavior
group by item_purchased
order by discount_rate desc limit 5;

#Segments customers into new,returning,and loyal based on their total number of previous purchases, and show the count of 
#each segments
select 
 case
  when previous_purchases =1  then "new"
  when previous_purchases between 2 and 10  then "returning"
  else "loyal"
 end as segments, count(*) as total_customers
from behavior
group by segments;

#top 3 most purchased product within each category
select count(item_purchased), category from behavior
group by category
limit 5;

#Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*)
from behavior
where previous_purchases>5
group by subscription_status;

# What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue from behavior
group by age_group
order by revenue desc;

#Checking the subscribers who are female
select count(customer_id) from behavior
where subscription_status="Yes" and gender="Female";





